#!/usr/bin/env bash
#
# dns-snapshot.sh — pull every DNS record from the Cloudflare zone
# for coincync.network and emit a portable snapshot. The output is
# ready to be replayed at deSEC, Hetzner DNS, or any other DNS
# provider as part of the failover preparation in
# docs/operations/DNS_FAILOVER.md.
#
# Requirements:
#   CF_API_TOKEN  — Cloudflare API token with `Zone:DNS:Read` scope
#                   (create at https://dash.cloudflare.com/profile/api-tokens)
#   CF_ZONE_ID    — the zone ID for coincync.network. Find at
#                   https://dash.cloudflare.com/<account>/coincync.network
#                   in the right-side panel under "API".
#   jq            — installed.
#
# Usage:
#   CF_API_TOKEN=... CF_ZONE_ID=... ./scripts/dns-snapshot.sh
#
# Output:
#   deploy/dns-snapshot-YYYYMMDD.json (committed to repo as
#   the canonical record-set; rotate quarterly).
#   deploy/dns-snapshot-YYYYMMDD.bind (BIND zonefile-style for
#   easy paste into provider control panels).
#
# Idempotent. Safe to run repeatedly. Two snapshots taken minutes
# apart should diff cleanly except for SOA serial.

set -euo pipefail

if [ -z "${CF_API_TOKEN:-}" ] || [ -z "${CF_ZONE_ID:-}" ]; then
  echo "ERROR: CF_API_TOKEN and CF_ZONE_ID must be set." >&2
  echo "" >&2
  echo "  export CF_API_TOKEN=<your_token>" >&2
  echo "  export CF_ZONE_ID=<your_zone_id>" >&2
  echo "" >&2
  echo "  See https://developers.cloudflare.com/fundamentals/api/get-started/create-token/" >&2
  exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "ERROR: jq is required. Install it (e.g., apt install jq)." >&2
  exit 1
fi

OUT_DIR="deploy"
mkdir -p "$OUT_DIR"
DATE=$(date -u +%Y%m%d)
JSON_OUT="$OUT_DIR/dns-snapshot-$DATE.json"
BIND_OUT="$OUT_DIR/dns-snapshot-$DATE.bind"

echo "Fetching DNS records from Cloudflare zone $CF_ZONE_ID..."

# Fetch records (paginated; CF default is 100/page, plenty for our zone)
RAW=$(curl -fsSL \
  -H "Authorization: Bearer $CF_API_TOKEN" \
  -H "Content-Type: application/json" \
  "https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/dns_records?per_page=200")

# Verify the API call succeeded
SUCCESS=$(echo "$RAW" | jq -r '.success')
if [ "$SUCCESS" != "true" ]; then
  echo "ERROR: API call failed:" >&2
  echo "$RAW" | jq '.errors' >&2
  exit 1
fi

# Pull the records, sort for deterministic output
echo "$RAW" | jq '.result | sort_by(.name, .type) | map({
  name,
  type,
  content,
  ttl,
  proxied,
  comment
})' > "$JSON_OUT"

RECORD_COUNT=$(jq 'length' "$JSON_OUT")
echo "  saved $RECORD_COUNT records to $JSON_OUT"

# Also emit a BIND-style zonefile for easy human review and provider
# import. Cloudflare's API doesn't return SOA/NS records by default,
# so this is records-only — perfect for replaying at a SECONDARY
# provider that will manage its own SOA/NS.
{
  echo "; CoinCync DNS snapshot — $DATE"
  echo "; Source: Cloudflare zone $CF_ZONE_ID"
  echo "; Generated by scripts/dns-snapshot.sh"
  echo "; "
  echo "; Replay at secondary provider (e.g. deSEC) by parsing this"
  echo "; or pasting individual records into the provider's UI."
  echo ";"
  jq -r '.[] | "\(.name)\t\(.ttl)\tIN\t\(.type)\t\(.content)\(if .proxied then " ; cf-proxied" else "" end)"' "$JSON_OUT"
} > "$BIND_OUT"
echo "  saved BIND-style zonefile to $BIND_OUT"

echo ""
echo "Next steps (per docs/operations/DNS_FAILOVER.md):"
echo "  1. Commit $JSON_OUT to the repo (it's not secret)."
echo "  2. Open the secondary provider (deSEC at https://desec.io)."
echo "  3. Import / paste records from $BIND_OUT."
echo "  4. Verify with: dig @ns1.desec.io coincync.network A"
echo "  5. Rotate this snapshot quarterly."
