//! Fuzz target for cyncswap state-file deserialization.
//!
//! State files at `~/.coincync/swap.json` are JSON written by save,
//! read by every subsequent `cyncswap` invocation. An attacker with
//! filesystem write to that path crafts arbitrary JSON; the v2 schema
//! (this tree, post-HMAC) is supposed to reject everything except a
//! file accompanied by a valid HMAC sidecar.
//!
//! This fuzz feeds random bytes through SwapStore::load to exercise:
//!   - serde_json's depth + width parsing
//!   - the v1-rejection path (UnsupportedVersion)
//!   - the HMAC verification path (IntegrityFailure)
//!   - the missing-sidecar path (HmacKeyMissing)
//!   - the field-typing path (Role enum, State enum, integer ranges)
//!
//! A panic anywhere = local-DoS at minimum; if reachable from a state
//! file generated by network input (future automation), a remote-DoS.

#![no_main]

use libfuzzer_sys::fuzz_target;

fuzz_target!(|data: &[u8]| {
    use coincync_swap::state::SwapStore;
    use std::io::Write;

    // Each iteration writes the fuzz bytes to a temp file and tries to
    // load it via SwapStore. The sidecar key file is intentionally NOT
    // created so the HMAC-missing path gets exercised. Whether the
    // bytes parse as JSON, parse as v1 (rejected), parse as v2 with
    // missing sidecar, or fail outright at serde — none of those
    // paths may panic.
    let tmp_dir = std::env::temp_dir().join(format!(
        "coincync-fuzz-state-{}",
        std::process::id()
    ));
    let _ = std::fs::create_dir_all(&tmp_dir);
    let state_path = tmp_dir.join("swap.json");

    {
        // Write + drop the file handle before load (so load reads fresh)
        if let Ok(mut f) = std::fs::File::create(&state_path) {
            let _ = f.write_all(data);
        }
    }

    let store = SwapStore::new(&state_path);
    // The whole point: this must never panic regardless of `data`.
    let _ = store.load();

    // Clean up so the next iteration writes fresh
    let _ = std::fs::remove_file(&state_path);
});
